package api

import (
	"fmt"
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger"

	"github.com/adit-prawira/neko/internal/shared"

	// Generated by `make swag`. Registers the OpenAPI spec with the swag
	// runtime registry so http-swagger can serve it. Do not import for
	// side effects only — the blank import is intentional.
	_ "github.com/adit-prawira/neko/internal/api/docs"
)

func buildRoutes(s *Server) http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /health", s.HandleHealth)
	mux.HandleFunc("POST /v1/collections", s.HandleCreateCollection)
	mux.HandleFunc("GET /v1/collections", s.HandleGetCollections)
	mux.HandleFunc("GET /v1/collections/{name}", s.HandleGetCollection)
	mux.HandleFunc("DELETE /v1/collections/{name}", s.HandleDropCollection)
	mux.HandleFunc("POST /v1/collections/{name}/search", s.HandleSearchCollection)
	mux.HandleFunc("POST /v1/collections/{name}/vectors", s.HandleInsertVector)
	mux.HandleFunc("POST /v1/collections/{name}/vectors/batch", s.HandleInsertManyVector)

	mux.HandleFunc("GET /v1/collections/{name}/vectors/{id}", s.HandleGetVector)
	mux.HandleFunc("PUT /v1/collections/{name}/vectors/{id}", s.HandleUpsertVector)
	mux.HandleFunc("DELETE /v1/collections/{name}/vectors/{id}", s.HandleDeleteVector)
	mux.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
		message := fmt.Sprintf("route %s %s is not found", r.Method, r.URL.Path)
		WriteHairball(rw, http.StatusNotFound, shared.HairballNotFound.String(), message)
	})

	// Swagger UI at /swagger/index.html; raw spec at /swagger/doc.json.
	// Spec is embedded into the binary by the generated docs package
	// (`make swag` produces `internal/api/docs/docs.go` with a //go:embed).
	mux.Handle("GET /swagger/", httpSwagger.Handler(httpSwagger.URL("/swagger/doc.json")))

	return mux
}
